.TH CONVERT2OSM 1 2010\-07\-15 0.99.4 "Convert a FoxtrotGPS logfile to OSM"

.SH NAME
convert2osm \- converts FoxtrotGPS logfiles into .osm files

.SH SYNOPSIS
\fBconvert2osm\fR logfiles*.log

.SH DESCRIPTION
converts \fIFoxtrotGPS\fR(1) .csv logfiles into .osm files for processing in JOSM. It creates for each input .log one .osm file.

.SH OPTIONS
convert2osm has no options.

.SH SEE ALSO
\fIFoxtrotGPS\fR(1),
\fIconvert2gpx\fR(1).

.SH HOMEPAGE
More information about FoxtrotGPS can be found at <\fIhttp://www.foxtrotgps.org/\fR>.

.SH AUTHOR
FoxtrotGPS is a community developed fork from tangoGPS lead by Joshua Judson Rosen <\fIrozzin@geekspace.com\fR>. tangoGPS was written by Marcus Bauer <\fImarcus.bauer@gmail.com\fR>.
