.TH CONVERT2GPX 1 2010\-07\-15 0.99.4 "Convert a FoxtrotGPS logfile to GPX"

.SH NAME
convert2gpx \- converts a FoxtrotGPS logfile to GPX

.SH SYNOPSIS
\fBconvert2gpx\fR logfile*.log > outfile.gpx

.SH DESCRIPTION
Convert a FoxtrotGPS logfile to GPX.

.SH OPTIONS
convert2gpx has no options.

.SH SEE ALSO
\fIFoxtrotGPS\fR(1),
\fIconvert2osm\fR(1).

.SH HOMEPAGE
More information about FoxtrotGPS can be found online at its website \%<\fIhttp://www.foxtrotgps.org/\fR>.

.SH AUTHOR
FoxtrotGPS is a community developed fork from tangoGPS lead by Joshua Judson Rosen \%<\fIrozzin@geekspace.com\fR>. tangoGPS was written by Marcus Bauer \%<\fImarcus.bauer@gmail.com\fR>.
