The following packages must be installed before this one can be built
or installed:

    * pkg-config <http://pkg-config.freedesktop.org/>
    * GLib 2.x <http://www.gtk.org/>
    * GTK+ 2.x <http://www.gtk.org/>
    * libglade 2.x <http://ftp.acc.umu.se/pub/GNOME/sources/libglade/2.6/>
    * GConf 2.x <http://www.gnome.org/projects/gconf/>
    * libcurl <http://curl.haxx.se/>
    * SQLite 3 <http://www.sqlite.org/>
    * libexif <http://libexif.sourceforge.net/>
    * libxml2 <http://xmlsoft.org/>
    * libgps >= 2.90 <http://gpsd.berlios.de/>
    * intltool >= 0.23 <http://freedesktop.org/wiki/Software/intltool>

In order to interface with the Zephyr HxM heartrate-monitor,
the following must be installed before FoxtrotGPS is built or installed:

    * BlueZ <http://www.bluez.org/>

In order to make use of the photo-geotagging features in this package,
the following additional packages must also be installed for use at
run-time:

    * gpscorrelate <http://freefoote.dview.net/linux_gpscorr.html>
    * jhead <http://www.sentex.net/~mwandel/jhead/>


If you're building from Bazaar, you also need:

    * The `makeinfo' command from GNU Texinfo
          <http://www.gnu.org/software/texinfo/>
    * GNU help2man <http://www.gnu.org/software/help2man/>
    * The `convert' command from ImageMagick <http://www.imagemagick.org/>

If you want to generate documentation in PDF, PostScript, or DVI format,
then you'll also need:

    * The GNU Texinfo suite <http://www.gnu.org/software/texinfo/>
    * A TeX implementation like TeX Live <http://www.tug.org/texlive/>
