.TH FOXTROTGPS 1 2010\-07\-15 0.99.4 "GTK+ mapping and GPS application"

.SH NAME
FoxtrotGPS \- GTK+ mapping and GPS application

.SH SYNOPSIS
\fBfoxtrotgps\fR [\fB\-\-fullscreen\fR]

.SH DESCRIPTION
FoxtrotGPS is a map and GPS application. By default, it uses maps from Openstreetmap.

.SH OPTIONS
.TP
\fB\-\-fullscreen\fR
Start in fullscreen mode

.SH SEE ALSO
\fIconvert2gpx\fR(1),
\fIconvert2osm\fR(1).

.SH HOMEPAGE
More information about FoxtrotGPS can be found at <\fIhttp://www.foxtrotgps.org/\fR>.

.SH AUTHOR
FoxtrotGPS is a community developed fork from tangoGPS lead by Joshua Judson Rosen <\fIrozzin@geekspace.com\fR>. tangoGPS was written by Marcus Bauer <\fImarcus.bauer@gmail.com\fR>.
