.TH FOXTROTGPS 1 2010\-07\-15 0.99.4 "GTK+ mapping and GPS application"

.SH NAME
FoxtrotGPS \- GTK+ mapping and GPS application

.SH SYNOPSIS
\fBfoxtrotgps\fR [\fB\-\-fullscreen\fR]

.SH DESCRIPTION
.PP
FoxtrotGPS is a map and GPS application. By default, it uses maps from Openstreetmap.
.PP
Clicking anywhere on the map pops up a menu of common operations.
Click and drag the map to pan.
.PP
FoxtrotGPS can be used to geotag photographs that were taken while
logging a GPS track, and can show icons on the map indicating
where the photographs were taken; this is done by correlating
timestamps in JPEG EXIF data with timestamps in the GPS track,
and the following additional packages must also be installed
for use at run-time in order to make use of this feature:

    * gpscorrelate <http://freefoote.dview.net/linux_gpscorr.html>
    * jhead <http://www.sentex.net/~mwandel/jhead/>


.SH OPTIONS
.TP
\fB\-\-fullscreen\fR
Start in fullscreen mode

.SH SEE ALSO
\fIconvert2gpx\fR(1),
\fIconvert2osm\fR(1).

.SH HOMEPAGE
More information about FoxtrotGPS can be found at <\fIhttp://www.foxtrotgps.org/\fR>.

.SH AUTHOR
FoxtrotGPS is a community developed fork from tangoGPS lead by Joshua Judson Rosen <\fIrozzin@geekspace.com\fR>. tangoGPS was written by Marcus Bauer <\fImarcus.bauer@gmail.com\fR>.
