#!/usr/bin/perl

# (C)2008 Marcus Bauer, License: GPLv2, marus.bauer@gmail.com

#
# helper for FoxtrotGPS to geocode photos
#

# needs: gpscorrelate, sqlite3

# input:
# - .log or .gpx file
# - photo list
# - timezone
# - correction

# logic:
# - convert to gpx
# - correlate

# gpscorrelate -g foo.gpx -z timezone --max-dist 120 --photooffset 5 p1.jpg ...

$geocode_track = $ARGV[0];
$geocode_dir   = $ARGV[1];
$timezone      = $ARGV[2];
$correction    = $ARGV[3];

#===================  MAIN  ====================

use File::Temp;

print STDERR "
VARS: 
  geocode_track = $ARGV[0];
  geocode_dir   = $ARGV[1];
  timezone      = $ARGV[2];
  correction    = $ARGV[3];
";

&test_for_helper_programs();
&get_photos_from_dir();

&convert2gpx();
&correlate();

#==================  END MAIN  ==================

sub test_for_helper_programs()
{
	# sqlite3, gpscorrelate

	$missing_prog = 0;

	if(system("sqlite3") == -1)		 { $install .= " sqlite3, ";	$missing_prog = 1;};
	if(system("gpscorrelate -h >/dev/null")  == -1)	 { $install .= " gpscorrelate"; 	$missing_prog = 1;};

	$error_msg = 	"Hello, I couldn't find the following helper programs: \n\n" .
			"   $install \n\n" .
			"-> You can find them in your Linux distribution.\n\n" .
			"Please install them first and try again.\n";

	if($missing_prog) {print STDOUT $error_msg;
	exit;}
}

sub get_photos_from_dir()
{
	opendir(DIR, $geocode_dir) || die("Cannot open directory");
	@photos= readdir(DIR);
	closedir(DIR);
}

sub convert2gpx
{
	# test if *.log 
	if($geocode_track =~ /\.log$/)
	{
		&do_convert2gpx();
	}
}


sub correlate
{
	#
	# construct command line
	#

	chdir($geocode_dir);

	foreach(@photos)
	{
		if(	-f "$_"   && 
			( ( $_ =~ /\.jpg$/i ) ||
			  ( $_ =~ /\.jpeg$/i)
			)
		  )
		{
			push (@photo_list, $_);
		}
		else { print STDERR "not a file: $_ \n"; }
	}

	# gpscorrelate ... 
	system ("gpscorrelate",
	        "-g", $geocode_track,
	        "-z",  $timezone,
	        "--max-dist", 120,
	        "--photooffset", $correction,
	        @photo_list);
	print "\n";

}


#=========== END MAIN FUNCTIONS, START HELPER FUNCTIONS ===========


sub do_convert2gpx
{
	
#---  open track logfile ---
	
open (INFILE, $geocode_track) or die $!;
$outfile = File::Temp->new() or die $!;

	
#--- start GPX ---

$gpx = <<EOT
<?xml version="1.0" encoding="UTF-8"?>
<gpx	version="1.0"
	creator="convert2gpx.pl http://www.foxtrotgps.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.topografix.com/GPX/1/0"
	xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">

<trk>
<trkseg>
EOT
;


while (<INFILE>)
{

@arr = split(',',$_);
chop @arr[6];

$gpx .= <<EOT
<trkpt lat="@arr[0]" lon="@arr[1]">
  <ele>@arr[2]</ele>
  <speed>@arr[3]</speed>
  <course>@arr[4]</course>
  <fix>3d</fix>
  <hdop>@arr[5]</hdop>
  <time>@arr[6]</time>
</trkpt>
EOT
;

} #end while()


$gpx .= <<EOT
</trkseg>
</trk>
</gpx>
EOT
;



print $outfile $gpx;
$geocode_track = $outfile->filename;

print STDERR "track: $geocode_track\n"
}
